server {
    listen 80;
    server_name _; # Replace with domain name or Public Elastic IP later

    # Increase max upload limits for photos & videos
    client_max_body_size 100M;

    location = /favicon.ico { access_log off; log_not_found off; }

    # Django static files path
    location /static/ {
        alias /home/ubuntu/car_backend/staticfiles/;
    }

    # Django media/upload files path
    location /media/ {
        alias /home/ubuntu/car_backend/media/;
    }

    # Proxy all requests to Gunicorn socket
    location / {
        include proxy_params;
        proxy_pass http://unix:/run/gunicorn.sock;
    }
}
