# Generated by Django 6.0.6 on 2026-06-23 05:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CarInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('km_driven', models.IntegerField()),
                ('fuel_type', models.CharField(max_length=15)),
                ('transmission', models.CharField(max_length=15)),
                ('expected_price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('contact_name', models.CharField(max_length=100)),
                ('contact_phone', models.CharField(max_length=15)),
                ('city', models.CharField(max_length=50)),
                ('preferred_inspection_date', models.DateField()),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Scheduled', 'Scheduled for Inspection'), ('Inspected', 'Inspected'), ('Completed', 'Sold to Spinny'), ('Cancelled', 'Cancelled')], default='Pending', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='car_inquiries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
