# Generated by Django 6.0.6 on 2026-06-23 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinquiry',
            name='admin_commission',
            field=models.DecimalField(decimal_places=2, default=0.0, help_text='Internal commission set by admin', max_digits=12),
        ),
    ]
