# Generated by Django 6.0.6 on 2026-06-23 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_carinquiry_admin_commission'),
    ]

    operations = [
        migrations.AddField(
            model_name='carinquiry',
            name='main_image',
            field=models.ImageField(blank=True, null=True, upload_to='inquiry_images/'),
        ),
        migrations.AddField(
            model_name='carinquiry',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='inquiry_videos/'),
        ),
    ]
