# Generated by Django 6.0.6 on 2026-06-23 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=50)),
                ('model', models.CharField(max_length=50)),
                ('variant', models.CharField(blank=True, max_length=50, null=True)),
                ('year', models.IntegerField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('km_driven', models.IntegerField()),
                ('fuel_type', models.CharField(choices=[('Petrol', 'Petrol'), ('Diesel', 'Diesel'), ('CNG', 'CNG'), ('Electric', 'Electric'), ('Hybrid', 'Hybrid')], max_length=15)),
                ('transmission', models.CharField(choices=[('Manual', 'Manual'), ('Automatic', 'Automatic')], max_length=15)),
                ('body_type', models.CharField(choices=[('Hatchback', 'Hatchback'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('MUV', 'MUV'), ('Luxury', 'Luxury')], max_length=20)),
                ('owner_count', models.IntegerField(default=1)),
                ('registration_state', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=50)),
                ('location_hub', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('available', 'Available'), ('reserved', 'Reserved'), ('sold', 'Sold')], default='available', max_length=15)),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to='car_images/')),
                ('mileage', models.DecimalField(blank=True, decimal_places=2, help_text='kmpl or km/kg', max_digits=5, null=True)),
                ('engine_displacement', models.IntegerField(blank=True, help_text='in cc', null=True)),
                ('max_power', models.CharField(blank=True, max_length=50, null=True)),
                ('torque', models.CharField(blank=True, max_length=50, null=True)),
                ('seats', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='car_images/gallery/')),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='cars.car')),
            ],
        ),
        migrations.CreateModel(
            name='InspectionReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('overall_rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('engine_rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('exterior_rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('interior_rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('suspension_rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('brakes_rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('engine_sound_ok', models.BooleanField(default=True)),
                ('exhaust_smoke_ok', models.BooleanField(default=True)),
                ('clutch_gear_ok', models.BooleanField(default=True)),
                ('ac_cooling_ok', models.BooleanField(default=True)),
                ('steering_ok', models.BooleanField(default=True)),
                ('suspension_sound_ok', models.BooleanField(default=True)),
                ('tyres_ok', models.BooleanField(default=True)),
                ('airbags_intact', models.BooleanField(default=True)),
                ('inspector_notes', models.TextField(blank=True, null=True)),
                ('inspected_date', models.DateField(auto_now_add=True)),
                ('car', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_report', to='cars.car')),
            ],
        ),
    ]
