# Generated by Django 6.0.6 on 2026-06-23 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='car_videos/'),
        ),
        migrations.AddField(
            model_name='car',
            name='video_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
